force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>LeaveId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>This represents the status of the leave.</description>
    <inlineHelpText>Leave Status</inlineHelpText>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Date_From__c.field-meta.xml
<CustomField>
    <fullName>Date_From__c</fullName>
    <description>The start date for leave of absence.</description>
    <inlineHelpText>Enter the start date for leave of absence.</inlineHelpText>
    <label>Date From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Date_To__c.field-meta.xml
<CustomField>
    <fullName>Date_To__c</fullName>
    <description>The end date for the leave of absence.</description>
    <inlineHelpText>Enter end date for leave of absence.</inlineHelpText>
    <label>Date To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Leave_For__c.field-meta.xml
<CustomField>
    <fullName>Leave_For__c</fullName>
    <description>Master Relationship between Contact &amp; Leave objects.</description>
    <inlineHelpText>Delete a contact, all leaves for associated contact are deleted. 
Delete a leave, only leave is deleted.</inlineHelpText>
    <label>Leave For</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leaves</relationshipLabel>
    <relationshipName>Leaves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/ofHours__c.field-meta.xml
<CustomField>
    <fullName>ofHours__c</fullName>
    <description>This represents the number of hours for leave of absence.</description>
    <inlineHelpText>Enter the number of hours for user&#39;s leave of absence.</inlineHelpText>
    <label>Number of Hours</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Type_of_Leave__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Leave__c</fullName>
    <label>Type of Leave</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP_LeaveDetails.cls
public class AP_LeaveDetails {

/*
* author : Hashim Alleemudder - alleemudder.hashim@accenture.com
* description : Method to get the list of Leave details for a particular Contact Owner.
* date : 26/03/2019
* params : Contact Owner Name - The Name of the Contact Owner.
*/ 
    /*@AuraEnabled
    public static List<Leave__c> getLeaveDetails(String ctName){
        //Initialising list to contain leave details of contact.
        List<Leave__c> leaveDetailsList = new List<Leave__c>();
        //Query Leave Details
        leaveDetailsList = [SELECT ID, ofHours__c, Date_From__c, Date_To__c, Approval_Status__c, Leave_For__c
                            FROM Leave__c
                            WHERE Leave_For__r.Name =: ctName
                            LIMIT 10];
        return leaveDetailsList;
    }*/
    
    @AuraEnabled
    public static String getLeaveDetails(){
        //Initialising list to contain leave details of contact.
        List<Leave__c> leaveDetailsList = new List<Leave__c>();
        //Query Leave Details
        leaveDetailsList = [SELECT ID, Name, Type_of_Leave__c, ofHours__c, Date_From__c, Date_To__c, Approval_Status__c, Leave_For__r.Name
                            FROM Leave__c
                            LIMIT 50];
        String leaveListSerialize = JSON.serialize(leaveDetailsList);
        return leaveListSerialize;
    }
    
}